In [311]:
PRE_DIR        <- "../../data/preprocessed_rds_files"
BEFORE_PRE_DIR <- "../../data/before_sample_filtering_preprocessed_rds_files"
CLIN_DIR       <- "../../data/raw_clinical_rds_files"
DEG_DIR        <- "../../data/deg_rds_files"
RESULTS_DIR    <- "../../results/deg"
DATA_DIR       <- "../../data"

datasets        <- c("GSE42568", "GSE21653", "GSE20711", "GSE88770")
SIGNATURE_GENES <- c("TSLP", "BIRC5", "S100B", "MDK", "S100P", "RARRES3", "BLNK", "ACO1")

RAW_RFS_COLS <- c(
    GSE42568 = "relapse free survival time_days:ch1",
    GSE21653 = "dfs time (months):ch1",
    GSE20711 = "t.rfs:ch1",
    GSE88770 = "drfs_or_last_contact_years:ch1"
)

In [312]:
view_raw_expr <- function(name) {
    expr <- readRDS(file.path(BEFORE_PRE_DIR, paste0(name, "_before_sample_filtering_expr.rds")))
    cat(sprintf("Raw Expression: %s -> %d rows x %d cols", name, nrow(expr), ncol(expr)))
    expr
}

view_raw_clinical <- function(name) {
    df <- readRDS(file.path(CLIN_DIR, paste0(name, "_raw_clinical.rds")))
    cat(sprintf("Raw Clinical: %s -> %d rows x %d cols\n\n", name, nrow(df), ncol(df)))
    for (col in colnames(df)) {
        vals     <- df[[col]]
        n_unique <- length(unique(vals))
        cat(sprintf("  %-50s [%d unique]  ", col, n_unique))
        if (n_unique <= 15) {
            cat(paste(sort(unique(vals)), collapse = " | "))
        } else {
            cat(class(vals), " e.g.", paste(head(unique(vals), 3), collapse = ", "), "...")
        }
        cat("\n")
    }
    df
}

view_preprocessed_expr <- function(name) {
    expr <- readRDS(file.path(PRE_DIR, paste0(name, "_expression_matrix.rds")))
    cat(sprintf("Preprocessed Expression: %s -> %d rows x %d cols", name, nrow(expr), ncol(expr)))
    expr
}

view_preprocessed_clinical <- function(name) {
    clinical <- readRDS(file.path(PRE_DIR, paste0(name, "_clinical_metadata.rds")))
    cat(sprintf("Preprocessed Clinical: %s -> %d rows x %d cols", name, nrow(clinical), ncol(expr)))
    clinical
}

summarise_rfs_time <- function(name) {
    df   <- readRDS(file.path(CLIN_DIR, paste0(name, "_raw_clinical.rds")))
    col  <- RAW_RFS_COLS[[name]]
    vals <- as.numeric(df[[col]])
    cat("RFS time raw distributionL: ", name, "\n")
    cat("Column:", col, "\n\n")
    print(summary(vals))
    invisible(vals)
}

# Dataset Expression + Raw Clinical + Clinical + RFS Time Summary

### GSE42568

In [313]:
head(view_raw_expr(datasets[1]))

Raw Expression: GSE42568 -> 54675 rows x 123 cols

  ID        GSM1045191 GSM1045192 GSM1045193 GSM1045194 GSM1045195 GSM1045196
1 1007_s_at 7.944225   7.083198   6.740806   8.884037   7.567701   7.683403
2 1053_at   5.256938   5.212302   4.995208   5.331575   5.346073   5.579011
3 117_at    4.934630   5.432387   4.693723   4.904832   5.065426   4.879720
4 121_at    6.608426   7.434570   7.226626   7.204006   6.974676   6.878121
5 1255_g_at 2.484290   3.690648   2.889619   2.749701   2.621078   2.508380
6 1294_at   7.019424   6.876868   7.620803   6.972236   7.225207   7.160766
  GSM1045197 GSM1045198 GSM1045199 ⋯ GSM1045303 GSM1045304 GSM1045305
1 6.844834   7.002953   7.307783   ⋯ 8.849172   9.390611   9.850697
2 5.675430   5.437027   5.854972   ⋯ 5.493730   5.527691   6.242621
3 4.723207   5.616361   5.249921   ⋯ 4.640617   5.481705   4.508405
4 6.699592   6.907204   6.549537   ⋯ 6.954195   6.568181   7.100799
5 2.514456   2.608083   2.522251   ⋯ 2.289100   2.366351   2.498756
6 6.851628   7.307723   7.030864   ⋯ 7.386927   7.393338   8.197274
  GSM1045306 GSM1045307 GSM1045308 GSM1045309 GSM1045310 GSM1045311
1 7.954908   8.865190   9.200912   8.675410   10.027844  9.295468
2 6.529160   5.420830   5.177657   5.784583    5.853110  5.581375
3 4.794507   4.628802   4.618140   5.349351    4.904169  4.990976
4 6.994747   6.304356   6.327677   7.107116    6.593784  6.550836
5 2.612875   2.400503   2.463490   2.525008    2.672050  2.544604
6 6.496519   7.466041   6.821004   7.589807    6.925438  7.312683
  Gene Symbol
1 DDR1 /// MIR4640
2 RFC2
3 HSPA6
4 PAX8
5 GUCA1A
6 MIR5193 /// UBA7

In [314]:
head(view_preprocessed_expr(datasets[1]))

Preprocessed Expression: GSE42568 -> 21655 rows x 122 cols

  gene_symbol GSM1045208 GSM1045209 GSM1045210 GSM1045211 GSM1045212 GSM1045213
1 A1BG        5.423835   6.177836   6.000779   6.153725   5.198928   5.242629
2 A1BG-AS1    4.606007   4.750312   4.544140   4.499905   4.402814   4.350368
3 A1CF        3.249699   3.358364   3.748739   3.697323   3.152932   3.489181
4 A2M         6.441683   6.698725   6.467165   6.700450   6.260376   7.345204
5 A2M-AS1     3.656200   3.981705   3.977325   4.022336   3.764769   4.151765
6 A2ML1       3.287500   3.200001   3.245106   3.785318   4.418914   3.529135
  GSM1045214 GSM1045215 GSM1045216 ⋯ GSM1045198 GSM1045199 GSM1045200
1 5.659892   5.220887   5.466822   ⋯ 5.502169   4.935021   5.449172
2 4.537319   4.373861   4.210245   ⋯ 4.117811   4.374573   4.358974
3 3.174822   3.018090   2.849808   ⋯ 3.181512   3.115969   3.063541
4 5.675768   7.077979   6.584333   ⋯ 7.182724   6.365128   7.039054
5 5.014600   4.478139   5.431021   ⋯ 5.391066   5.675315   4.924056
6 3.078615   2.988193   4.057908   ⋯ 3.241485   3.111028   3.254171
  GSM1045201 GSM1045202 GSM1045203 GSM1045204 GSM1045205 GSM1045206 GSM1045207
1 5.747786   4.936577   4.765647   5.085291   4.974527   5.028414   5.040149
2 4.091500   4.171603   4.210834   4.163235   3.704708   3.916655   3.738052
3 3.341375   2.944470   3.415830   2.825365   3.160324   3.341551   3.170451
4 6.704904   6.674221   6.583314   7.020678   6.683796   6.669373   6.431769
5 5.280325   5.746852   4.838510   5.557101   4.925182   4.823235   5.231356
6 3.188559   3.041860   3.253882   2.940904   3.011754   3.216768   3.156280

In [315]:
head(view_raw_clinical(datasets[1]))

Raw Clinical: GSE42568 -> 121 rows x 50 cols

  title                                              [121 unique]  character  e.g. Normal breast, N1_15_12_04, Normal breast, N4_14_12_04, Normal breast, N5_15_12_04 ...
  geo_accession                                      [121 unique]  character  e.g. GSM1045191, GSM1045192, GSM1045193 ...
  status                                             [1 unique]  Public on May 26 2013
  submission_date                                    [1 unique]  Nov 27 2012
  last_update_date                                   [1 unique]  Jul 30 2013
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [2 unique]  Breast tissue, cancer | Breast tissue, normal
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [2 unique]  tissue: breast cancer | tissue: normal breast
  characteristics_ch1.1                              [103 unique]  character  e.g. age: NA, age: 74.03, age: 67.26 ...
  characteristics_ch1.2                              [3 unique]  er_status: 0 | er_status: 1 | er_status: NA
  characteristics_ch1.3                              [25 unique]  character  e.g. size: NA, size: 0.6, size: 5 ...
  characteristics_ch1.4                              [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.5                              [3 unique]  lymph node status: 0 | lymph node status: 1 | lymph node status: NA
  characteristics_ch1.6                              [100 unique]  character  e.g. relapse free survival time_days: NA, relapse free survival time_days: 3026, relapse free survival time_days: 755 ...
  characteristics_ch1.7                              [3 unique]  relapse free survival event: 0 | relapse free survival event: 1 | relapse free survival event: NA
  characteristics_ch1.8                              [103 unique]  character  e.g. overall survival time_days: NA, overall survival time_days: 3026, overall survival time_days: 755 ...
  characteristics_ch1.9                              [3 unique]  overall survival event: 0 | overall survival event: 1 | overall survival event: NA
  treatment_protocol_ch1                             [1 unique]  Tissues were stored at -70°C/-80°C prior to RNA isolation.
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Samples were homogenised, on ice, in 1 ml TriReagent (Sigma; Poole, UK) and total RNA was subsequently isolated according to the manufacturer's instructions. RNA quantity and purity were assessed at 260 nm and 280 nm using a Nanodrop (ND-1000; Labtech. International); an Agilent Bioanalyser (Agilent 2100; Agilent Technologies) was used to assess RNA qualitatively after isolation and, subsequently, following biotin-labelling and after fragmentation.
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  100 ng of each specimen was amplified and labelled using the Affymetrix GeneChip Eukaryotic 2 Cycle Labelling Assays for Expression Analysis, (Affymetrix; 900494) according to the manufacturer's instructions (www.affymetrix.com/products/reagents/specific/cdna2.affx).
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Hybridisation solution (1 mol/l NaCl, 20 mmol/1 EDTA, 100 mmol/1 2-(N-morpholino) ethanesulfonic acid, and 0.01% Tween 20) was used to pre-hybridise Affymetrix U133 Plus 2.0 oligonucleotide microarrays for 10 minutes at 45°C and 60 rpm. The pre-hybridisation solution was removed and replaced with 200 μl hybridisation solution containing 0.05 μg/μl fragmented cRNA. The arrays were hybridised for 16 hours at 45°C and 60 rpm. Arrays were subsequently washed (Affymetrix Fluidics Station 400) and stained with streptavidin-phycoerythrin (Stain Buffer, 2 mg/ml acetylated BSA and 10 μg/ml streptavidin R-phycoerythrin; Molecular Probes, Inc., Eugene, OR).
  scan_protocol                                      [1 unique]  Arrays were scanned on an Affymetrix GCS GeneChip GeneArray scanner. Resulting data was analysed using GCOS, dCHIP, and GeneSpring (Agilent Technologies).
  description                                        [2 unique]  Breast cancer data. | Normal breast tissue data.
  data_processing                                    [1 unique]  All microarray data were called using the GC robust multichip average method (GC-RMA). R and Bioconductor - GCRMA package.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Colin ,,Clarke
  contact_email                                      [1 unique]  colin.clarke@dcu.ie
  contact_department                                 [1 unique]  NICB
  contact_institute                                  [1 unique]  Dublin City University
  contact_address                                    [1 unique]  Collin's Av.
  contact_city                                       [1 unique]  Dublin
  contact_zip/postal_code                            [1 unique]  Dublin 9
  contact_country                                    [1 unique]  Ireland
  supplementary_file                                 [121 unique]  character  e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045191/suppl/GSM1045191_N1_15_12_04.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045192/suppl/GSM1045192_N4_14_12_04.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045193/suppl/GSM1045193_N5_15_12_04.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  age:ch1                                            [103 unique]  character  e.g. NA, 74.03, 67.26 ...
  er_status:ch1                                      [3 unique]  0 | 1 | NA
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  lymph node status:ch1                              [3 unique]  0 | 1 | NA
  overall survival event:ch1                         [3 unique]  0 | 1 | NA
  overall survival time_days:ch1                     [103 unique]  character  e.g. NA, 3026, 755 ...
  relapse free survival event:ch1                    [3 unique]  0 | 1 | NA
  relapse free survival time_days:ch1                [100 unique]  character  e.g. NA, 3026, 755 ...
  size:ch1                                           [25 unique]  character  e.g. NA, 0.6, 5 ...
  tissue:ch1                                         [2 unique]  breast cancer | normal breast

           title                      geo_accession status
GSM1045191 Normal breast, N1_15_12_04 GSM1045191    Public on May 26 2013
GSM1045192 Normal breast, N4_14_12_04 GSM1045192    Public on May 26 2013
GSM1045193 Normal breast, N5_15_12_04 GSM1045193    Public on May 26 2013
GSM1045194 Normal breast, N6_14_12_04 GSM1045194    Public on May 26 2013
GSM1045195 Normal breast, P1_15_12_04 GSM1045195    Public on May 26 2013
GSM1045196 Normal breast, P10_26_1_05 GSM1045196    Public on May 26 2013
           submission_date last_update_date type channel_count
GSM1045191 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045192 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045193 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045194 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045195 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045196 Nov 27 2012     Jul 30 2013      RNA  1
           source_name_ch1       organism_ch1 characteristics_ch1   ⋯ age:ch1
GSM1045191 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045192 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045193 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045194 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045195 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045196 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
           er_status:ch1 grade:ch1 lymph node status:ch1
GSM1045191 NA            NA        NA
GSM1045192 NA            NA        NA
GSM1045193 NA            NA        NA
GSM1045194 NA            NA        NA
GSM1045195 NA            NA        NA
GSM1045196 NA            NA        NA
           overall survival event:ch1 overall survival time_days:ch1
GSM1045191 NA                         NA
GSM1045192 NA                         NA
GSM1045193 NA                         NA
GSM1045194 NA                         NA
GSM1045195 NA                         NA
GSM1045196 NA                         NA
           relapse free survival event:ch1 relapse free survival time_days:ch1
GSM1045191 NA                              NA
GSM1045192 NA                              NA
GSM1045193 NA                              NA
GSM1045194 NA                              NA
GSM1045195 NA                              NA
GSM1045196 NA                              NA
           size:ch1 tissue:ch1
GSM1045191 NA       normal breast
GSM1045192 NA       normal breast
GSM1045193 NA       normal breast
GSM1045194 NA       normal breast
GSM1045195 NA       normal breast
GSM1045196 NA       normal breast

In [316]:
head(view_preprocessed_clinical(datasets[1]))

Preprocessed Clinical: GSE42568 -> 121 rows x 118 cols

  geo_accession is_tumor rfs_event rfs_time er_status tumor_grade
1 GSM1045208    1        0         3026     1         2
2 GSM1045209    1        1          755     1         2
3 GSM1045210    1        0         3014     1         1
4 GSM1045211    1        1          406     1         3
5 GSM1045212    1        0         2225     0         3
6 GSM1045213    1        1          252     0         3
  lymph_node_status t_stage
1 1                 0.6
2 1                 5
3 0                 3.5
4 1                 1.5
5 0                 2.7
6 1                 5

In [317]:
summarise_rfs_time(datasets[1])

Warning message in summarise_rfs_time(datasets[1]):
"NAs introduced by coercion"

RFS time raw distributionL:  GSE42568
Column: relapse free survival time_days:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   84.0   595.8  1907.0  1633.2  2485.2  3026.0      17

### GSE21653

In [318]:
head(view_raw_expr(datasets[2]))

Raw Expression: GSE21653 -> 54613 rows x 268 cols

  ID        GSM540108 GSM540109 GSM540110 GSM540111 GSM540112 GSM540113
1 1007_s_at 10.343735 9.575994  10.205832 10.643041 10.926893 10.230111
2 1053_at    6.021293 6.156694   6.710895  7.513664  6.895131  6.368140
3 117_at     6.085259 6.140420   5.978487  6.108825  6.824378  6.440690
4 121_at     7.813140 7.803163   8.200998  7.848145  7.906104  7.291020
5 1255_g_at  2.904675 3.258130   3.401846  2.934258  2.925637  3.034741
6 1294_at    7.856463 7.734331   9.406229  7.170883  7.775025  8.634346
  GSM540114 GSM540115 GSM540116 ⋯ GSM540365 GSM540366 GSM540367 GSM540368
1 11.023431 10.039638 10.411611 ⋯ 10.666997 11.509220 11.144890 10.629969
2  6.756792  6.914100  6.804170 ⋯  6.724054  8.184394  6.680929  7.147298
3  6.391995  6.403060  6.558244 ⋯  7.514853  6.919280  5.352472  8.725935
4  7.174387  7.061505  7.588398 ⋯  7.706852  7.059599  7.379992  7.162970
5  2.883232  3.013251  3.174074 ⋯  2.846147  2.876281  3.085632  2.981247
6  8.219496  7.967642  8.442348 ⋯  8.857178  6.838197  8.153096  8.360628
  GSM540369 GSM540370 GSM540371 GSM540372 GSM540373 Gene Symbol
1 10.984374 9.974021  10.709648 11.791408 10.051067 DDR1 /// MIR4640
2  8.574534 7.697865   7.261706  8.535019  7.892871 RFC2
3  7.582938 6.973274   6.842967  6.857275  6.610817 HSPA6
4  8.006837 7.871258   7.801191  7.652344  7.754103 PAX8
5  3.198020 3.124897   3.110327  3.110366  2.892730 GUCA1A
6  7.378396 8.476990   7.600028  7.086442  8.655083 MIR5193 /// UBA7

In [319]:
head(view_preprocessed_expr(datasets[2]))

Preprocessed Expression: GSE21653 -> 21655 rows x 242 cols

  gene_symbol GSM540108 GSM540111 GSM540112 GSM540113 GSM540114 GSM540115
1 A1BG        6.146570  5.717083  5.667256  5.821602  5.582540  5.678218
2 A1BG-AS1    5.192952  4.476920  5.047257  5.420414  4.874277  4.710615
3 A1CF        4.136334  3.887450  3.876345  3.737222  3.619344  3.747788
4 A2M         7.202705  8.021876  7.659437  8.497944  8.218462  8.664218
5 A2M-AS1     5.378281  5.039355  4.568131  5.923578  5.995361  6.468561
6 A2ML1       4.452781  3.829404  3.678200  3.882873  3.741898  3.987309
  GSM540116 GSM540117 GSM540118 ⋯ GSM540364 GSM540365 GSM540366 GSM540367
1 6.570997  5.448448  6.015925  ⋯ 5.768699  5.915461  5.332402  5.880671
2 5.320223  4.697236  5.137198  ⋯ 4.654715  4.821310  4.533131  4.630453
3 3.939471  3.905798  4.071506  ⋯ 3.730873  3.814982  3.800488  3.891974
4 8.092863  7.513445  8.136513  ⋯ 8.240868  8.781016  8.344433  7.989748
5 4.866476  4.699715  6.430267  ⋯ 6.963635  5.482779  4.767218  5.862145
6 3.973815  3.813723  4.306715  ⋯ 4.038272  3.880021  4.943441  4.137063
  GSM540368 GSM540369 GSM540370 GSM540371 GSM540372 GSM540373
1 5.785042  6.160731  5.855461  5.794792  5.933755  5.574898
2 4.559740  4.400831  4.790866  4.519228  4.606000  4.458904
3 3.807973  3.815930  3.925795  3.902201  4.093958  3.588490
4 9.159850  8.391154  7.977827  8.225967  8.341430  8.060287
5 5.259731  4.957411  4.985096  5.038558  4.602791  6.741662
6 4.040179  3.848122  4.733253  4.720478  4.688482  3.704352

In [320]:
head(view_raw_clinical(datasets[2]))

Raw Clinical: GSE21653 -> 266 rows x 62 cols

  title                                              [266 unique]  character  e.g. BC1, BC2, BC3 ...
  geo_accession                                      [266 unique]  character  e.g. GSM540108, GSM540109, GSM540110 ...
  status                                             [1 unique]  Public on May 05 2010
  submission_date                                    [1 unique]  May 04 2010
  last_update_date                                   [2 unique]  Aug 19 2011 | Aug 28 2018
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [1 unique]  human breast cancer tumors
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [60 unique]  character  e.g. age at diagnosis: 67, age at diagnosis: 47, age at diagnosis: 41 ...
  characteristics_ch1.1                              [9 unique]  histology: IDC | histology: ILC | histology: MIX | histology: MUC | histology: other | histology: TUB | pn: 1 | pn: NA | pt: pT2
  characteristics_ch1.2                              [8 unique]  pn: 0 | pn: 1 | pn: NA | pt: pT1 | pt: pT2 | pt: pT3 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.3                              [9 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | pn: 0 | pn: 1 | pn: NA | sbr grade: 2 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.4                              [9 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | pr ihc: 0 | pr ihc: NA | sbr grade: 1 | sbr grade: 2 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.5                              [8 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | erbb2: 1 | erbb2: NA | pr ihc: 0 | pr ihc: 1 | pr ihc: NA
  characteristics_ch1.6                              [8 unique]  erbb2: 0 | erbb2: 1 | erbb2: NA | p53 ihc: 1 | p53 ihc: NA | pr ihc: 0 | pr ihc: 1 | pr ihc: NA
  characteristics_ch1.7                              [7 unique]  erbb2: 0 | erbb2: 1 | erbb2: NA | ki67 ihc: 1 | ki67 ihc: NA | p53 ihc: 1 | p53 ihc: NA
  characteristics_ch1.8                              [7 unique]  dfs evt: 1 | dfs evt: NA | ki67 ihc: 1 | ki67 ihc: NA | p53 ihc: 0 | p53 ihc: 1 | p53 ihc: NA
  characteristics_ch1.9                              [9 unique]  dfs evt: 0 | dfs evt: 1 | dfs evt: NA | dfs time (months): 16.30 | dfs time (months): 19.65 | ki67 ihc: 0 | ki67 ihc: 1 | ki67 ihc: NA | molecular subtype: ERBB2
  characteristics_ch1.10                             [12 unique]  dfs evt: 0 | dfs evt: 1 | dfs evt: NA | dfs time (months): 0.00 | dfs time (months): 10.00 | dfs time (months): 113.77 | dfs time (months): 222.29 | dfs time (months): 37.62 | dfs time (months): 51.84 | molecular subtype: LuminalB | molecular subtype: Normal | tissue: breast cancer tumor
  characteristics_ch1.11                             [242 unique]  character  e.g. dfs time (months): 24.02, tissue: breast cancer tumor, dfs time (months): 58.15 ...
  characteristics_ch1.12                             [7 unique]   | molecular subtype: Basal | molecular subtype: ERBB2 | molecular subtype: LuminalA | molecular subtype: LuminalB | molecular subtype: Normal | tissue: breast cancer tumor
  characteristics_ch1.13                             [2 unique]   | tissue: breast cancer tumor
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Guanidinium isothiocyanate and centrifugation over a cesium chloride gradient.
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  Affymetrix standard protocol
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Affymetrix standard protocol
  scan_protocol                                      [1 unique]  Affymetrix standard protocol
  description                                        [1 unique]  n/a
  data_processing                                    [1 unique]  RMA using a quantile normalization
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Pascal,,FINETTI
  contact_email                                      [1 unique]  finettip@ipc.unicancer.fnclcc.fr
  contact_phone                                      [1 unique]  (33)+4 91 22 33 04
  contact_laboratory                                 [1 unique]  Molecular Oncology
  contact_department                                 [1 unique]  Centre de cancérologie de Marseille
  contact_institute                                  [1 unique]  Institut Paoli-Calmettes
  contact_address                                    [1 unique]  232 Bd Ste Marguerite
  contact_city                                       [1 unique]  Marseille
  contact_state                                      [1 unique]  BdR
  contact_zip/postal_code                            [1 unique]  13009
  contact_country                                    [1 unique]  France
  supplementary_file                                 [266 unique]  character  e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540108/suppl/GSM540108_160306-23.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540109/suppl/GSM540109_060406-05.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540110/suppl/GSM540110_200406-16.CEL.gz ...
  data_row_count                                     [1 unique]  54613
  relation                                           [265 unique]  character  e.g. Reanalyzed by: GSM781322, Reanalyzed by: GSM781323, Reanalyzed by: GSM781324 ...
  relation.1                                         [2 unique]   | Reanalyzed by: GSE119087
  age at diagnosis:ch1                               [60 unique]  character  e.g. 67, 47, 41 ...
  dfs evt:ch1                                        [3 unique]  0 | 1 | NA
  dfs time (months):ch1                              [242 unique]  character  e.g. 24.02, 16.30, 19.65 ...
  er ihc:ch1                                         [3 unique]  0 | 1 | NA
  erbb2:ch1                                          [3 unique]  0 | 1 | NA
  histology:ch1                                      [7 unique]  IDC | ILC | MIX | MUC | other | TUB
  ki67 ihc:ch1                                       [3 unique]  0 | 1 | NA
  molecular subtype:ch1                              [5 unique]  Basal | ERBB2 | LuminalA | LuminalB | Normal
  p53 ihc:ch1                                        [3 unique]  0 | 1 | NA
  pn:ch1                                             [3 unique]  0 | 1 | NA
  pr ihc:ch1                                         [3 unique]  0 | 1 | NA
  pt:ch1                                             [4 unique]  pT1 | pT2 | pT3
  sbr grade:ch1                                      [4 unique]  1 | 2 | 3 | NA
  tissue:ch1                                         [1 unique]  breast cancer tumor

          title geo_accession status                submission_date
GSM540108 BC1   GSM540108     Public on May 05 2010 May 04 2010
GSM540109 BC2   GSM540109     Public on May 05 2010 May 04 2010
GSM540110 BC3   GSM540110     Public on May 05 2010 May 04 2010
GSM540111 BC4   GSM540111     Public on May 05 2010 May 04 2010
GSM540112 BC5   GSM540112     Public on May 05 2010 May 04 2010
GSM540113 BC6   GSM540113     Public on May 05 2010 May 04 2010
          last_update_date type channel_count source_name_ch1
GSM540108 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540109 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540110 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540111 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540112 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540113 Aug 28 2018      RNA  1             human breast cancer tumors
          organism_ch1 characteristics_ch1  ⋯ erbb2:ch1 histology:ch1
GSM540108 Homo sapiens age at diagnosis: 67 ⋯ 0         IDC
GSM540109 Homo sapiens age at diagnosis: 47 ⋯ 1         NA
GSM540110 Homo sapiens age at diagnosis: 41 ⋯ 1         NA
GSM540111 Homo sapiens age at diagnosis: 62 ⋯ 1         IDC
GSM540112 Homo sapiens age at diagnosis: 60 ⋯ 0         IDC
GSM540113 Homo sapiens age at diagnosis: 51 ⋯ 0         IDC
          ki67 ihc:ch1 molecular subtype:ch1 p53 ihc:ch1 pn:ch1 pr ihc:ch1
GSM540108 NA           LuminalB              0           1      0
GSM540109 1            LuminalB              1           1      0
GSM540110 1            LuminalB              1           1      0
GSM540111 NA           ERBB2                 1           1      0
GSM540112 0            LuminalA              0           1      1
GSM540113 NA           Normal                0           1      0
          pt:ch1 sbr grade:ch1 tissue:ch1
GSM540108 pT2    2             breast cancer tumor
GSM540109 NA     3             breast cancer tumor
GSM540110 NA     3             breast cancer tumor
GSM540111 pT1    3             breast cancer tumor
GSM540112 pT2    2             breast cancer tumor
GSM540113 pT1    2             breast cancer tumor

In [321]:
head(view_preprocessed_clinical(datasets[2]))

Preprocessed Clinical: GSE21653 -> 241 rows x 118 cols

  geo_accession is_tumor rfs_event rfs_time
1 GSM540108     1        1          731.1688
2 GSM540111     1        1         1770.0860
3 GSM540112     1        1          871.1928
4 GSM540113     1        1          301.0516
5 GSM540114     1        1          226.1692
6 GSM540115     1        0         5755.5952

In [322]:
summarise_rfs_time(datasets[2])

RFS time raw distributionL:  GSE21653
Column: dfs time (months):ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   0.00   28.04   52.91   60.03   89.83  222.29      14

### GSE20711

In [323]:
head(view_raw_expr(datasets[3]))

Raw Expression: GSE20711 -> 54675 rows x 92 cols

  ID        GSM519722 GSM519723 GSM519724 GSM519725 GSM519726 GSM519727
1 1007_s_at 10.187052 9.652073  9.243115  9.665201  10.232769 10.278378
2 1053_at    7.127039 6.863698  7.034919  6.911693   7.634268  7.007954
3 117_at     6.887078 6.050344  6.631097  6.465884   6.318923  7.249174
4 121_at     6.885332 7.185804  7.044363  6.599302   6.764104  7.151394
5 1255_g_at  2.837355 2.647247  2.329934  2.563766   2.473097  2.483178
6 1294_at    7.572196 6.627245  7.435874  7.353535   6.128658  7.072954
  GSM519728 GSM519729 GSM519730 ⋯ GSM519804 GSM519805 GSM519806 GSM519807
1 10.099109 10.287591 10.173119 ⋯ 10.463529 9.595977  10.819352 9.782994
2  7.427445  8.161011  7.824778 ⋯  6.717380 7.132356   8.113843 6.127102
3  5.825132  5.704061  6.100853 ⋯  6.356327 6.384561   5.461238 6.716387
4  6.651394  7.008276  6.705128 ⋯  6.319033 6.335060   6.006954 6.253306
5  2.423432  2.306350  2.509102 ⋯  2.186710 2.513868   2.431490 2.514999
6  5.831950  6.968410  7.646905 ⋯  7.768421 7.509334   7.781010 7.015057
  GSM519808 GSM519809 GSM519810 GSM519811 GSM519812 Gene Symbol
1 9.221509  10.057569 9.604759  10.017669 9.780783  DDR1 /// MIR4640
2 6.751229   6.432357 6.711111   6.705162 6.357043  RFC2
3 6.643741   5.837846 6.927909   4.745112 7.269059  HSPA6
4 6.926910   7.095445 6.730393   6.428529 6.557090  PAX8
5 2.449755   2.529823 2.770067   2.807189 2.585510  GUCA1A
6 6.666444   6.719635 7.232949   7.803147 7.222269  MIR5193 /// UBA7

In [324]:
head(view_preprocessed_expr(datasets[3]))

Preprocessed Expression: GSE20711 -> 21655 rows x 89 cols

  gene_symbol GSM519722 GSM519723 GSM519724 GSM519725 GSM519726 GSM519727
1 A1BG        6.119304  6.479491  6.017579  6.061706  5.581822  5.745512
2 A1BG-AS1    4.600823  4.603668  5.055174  4.647037  4.182169  4.702075
3 A1CF        3.121685  3.268132  3.115821  3.169886  3.329781  3.369047
4 A2M         7.234631  7.518227  7.381913  7.575412  8.363513  7.212989
5 A2M-AS1     4.909697  5.186144  7.623446  6.109816  6.142342  5.984419
6 A2ML1       2.937211  2.967149  3.199144  2.913530  3.081503  5.443215
  GSM519728 GSM519729 GSM519730 ⋯ GSM519803 GSM519804 GSM519805 GSM519806
1 4.886712  5.426486  5.901916  ⋯ 6.828642  6.224153  5.904253  7.912051
2 4.326911  4.773466  4.570657  ⋯ 5.165543  5.413369  4.413916  5.295210
3 3.217963  3.303424  3.170489  ⋯ 3.436043  3.180104  3.173097  3.547779
4 7.100545  7.251371  7.344661  ⋯ 6.895032  7.326967  7.521037  6.383923
5 4.648674  5.765407  5.374764  ⋯ 4.911827  7.175151  6.366014  4.906894
6 3.253625  5.462837  2.760528  ⋯ 3.035323  2.656849  2.834887  3.471181
  GSM519807 GSM519808 GSM519809 GSM519810 GSM519811 GSM519812
1 5.955679  5.698015  6.037793  5.715892  5.262424  5.574846
2 4.995111  4.816337  4.585186  4.774603  4.412655  4.546656
3 3.180838  3.681620  3.463427  3.442144  3.177729  3.593152
4 7.135244  7.712773  7.493888  7.007678  7.672010  7.781730
5 5.463223  4.654847  5.819628  5.777034  6.470250  6.035571
6 2.745098  3.112381  3.015567  2.558184  3.231751  2.854460

In [325]:
head(view_raw_clinical(datasets[3]))

Raw Clinical: GSE20711 -> 90 rows x 60 cols

  title                                              [90 unique]  character  e.g. Breast tumor from patient P_1 (expression data), Breast tumor from patient P_2 (expression data), Breast tumor from patient P_3 (expression data) ...
  geo_accession                                      [90 unique]  character  e.g. GSM519722, GSM519723, GSM519724 ...
  status                                             [1 unique]  Public on Oct 19 2011
  submission_date                                    [1 unique]  Mar 09 2010
  last_update_date                                   [1 unique]  Jun 17 2021
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [2 unique]  Breast tumor | Normal breast tissue
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [1 unique]  quality control: 1
  characteristics_ch1.1                              [90 unique]  character  e.g. methylation barcode: 4690141010_D, methylation barcode: 4690141010_J, methylation barcode: 4690141011_A ...
  characteristics_ch1.2                              [5 unique]  subtypeihc: Basal | subtypeihc: HER2 | subtypeihc: LumA | subtypeihc: LumB | subtypeihc: Normal
  characteristics_ch1.3                              [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.4                              [3 unique]  node: 0 | node: 1 | node: NA
  characteristics_ch1.5                              [3 unique]  size (bin): 0 | size (bin): 1 | size (bin): NA
  characteristics_ch1.6                              [3 unique]  age (bin): 0 | age (bin): 1 | age (bin): NA
  characteristics_ch1.7                              [3 unique]  er status: 0 | er status: 1 | er status: NA
  characteristics_ch1.8                              [3 unique]  her2 status: 0 | her2 status: 1 | her2 status: NA
  characteristics_ch1.9                              [5 unique]  subtypege: Basal | subtypege: HER2+ | subtypege: LumA | subtypege: LumB | subtypege: NA
  characteristics_ch1.10                             [3 unique]  e.rfs: 0 | e.rfs: 1 | e.rfs: NA
  characteristics_ch1.11                             [86 unique]  character  e.g. t.rfs: 0.93, t.rfs: 1.22, t.rfs: 8.64 ...
  characteristics_ch1.12                             [3 unique]  e.os: 0 | e.os: 1 | e.os: NA
  characteristics_ch1.13                             [88 unique]  character  e.g. t.os: 8.28 y, t.os: 3.39 y, t.os: 8.64 y ...
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Isolation of RNA was performed using the Trizol method (Invitrogen) according to the manufacturers instructions and was purified using RNeasy mini-columns (Qiagen, Valencia, CA). The quality of the RNA obtained from each tumour sample was assessed based on the RNA profile generated by the bioanalyzer (Agilent Inc)olation of RNA was performed using the Trizol method (Invitrogen) according to the manufacturers instructions and was purified using RNeasy mini-columns (Qiagen, Valencia, CA). The quality of the RNA obtained from each tumour sample was assessed based on the RNA profile generated by the bioanalyzer (Agilent Inc).
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  Approximately 1 microgram of total RNA was processed to produce biotinylated cRNA targets.
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  standard Affymetrix procedures.
  scan_protocol                                      [1 unique]  standard Affymetrix procedures.
  description                                        [90 unique]  character  e.g. DNA9194-001.CEL, DNA9194-002.CEL, DNA9194-003.CEL ...
  data_processing                                    [1 unique]  RMA Bioconductor (default parameters) and log2 transformation.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Benjamin,,Haibe-Kains
  contact_email                                      [1 unique]  benjamin.haibe.kains@utoronto.ca
  contact_phone                                      [1 unique]  +14165818626
  contact_laboratory                                 [1 unique]  Bioinformatics and Computational Genomics
  contact_department                                 [1 unique]  Princess Margaret Research
  contact_institute                                  [1 unique]  Princess Margaret Cancer Centre
  contact_address                                    [1 unique]  610 University Avenue
  contact_city                                       [1 unique]  Toronto
  contact_state                                      [1 unique]  Ontario
  contact_zip/postal_code                            [1 unique]  M5G 2M9
  contact_country                                    [1 unique]  Canada
  supplementary_file                                 [90 unique]  character  e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519722/suppl/GSM519722.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519723/suppl/GSM519723.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519724/suppl/GSM519724.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  age (bin):ch1                                      [3 unique]  0 | 1 | NA
  e.os:ch1                                           [3 unique]  0 | 1 | NA
  e.rfs:ch1                                          [3 unique]  0 | 1 | NA
  er status:ch1                                      [3 unique]  0 | 1 | NA
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  her2 status:ch1                                    [3 unique]  0 | 1 | NA
  methylation barcode:ch1                            [90 unique]  character  e.g. 4690141010_D, 4690141010_J, 4690141011_A ...
  node:ch1                                           [3 unique]  0 | 1 | NA
  quality control:ch1                                [1 unique]  1
  size (bin):ch1                                     [3 unique]  0 | 1 | NA
  subtypege:ch1                                      [5 unique]  Basal | HER2+ | LumA | LumB | NA
  subtypeihc:ch1                                     [5 unique]  Basal | HER2 | LumA | LumB | Normal
  t.os:ch1                                           [88 unique]  character  e.g. 8.28 y, 3.39 y, 8.64 y ...
  t.rfs:ch1                                          [86 unique]  character  e.g. 0.93, 1.22, 8.64 ...

          title                                           geo_accession
GSM519722 Breast tumor from patient P_1 (expression data) GSM519722
GSM519723 Breast tumor from patient P_2 (expression data) GSM519723
GSM519724 Breast tumor from patient P_3 (expression data) GSM519724
GSM519725 Breast tumor from patient P_4 (expression data) GSM519725
GSM519726 Breast tumor from patient P_6 (expression data) GSM519726
GSM519727 Breast tumor from patient P_7 (expression data) GSM519727
          status                submission_date last_update_date type
GSM519722 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519723 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519724 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519725 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519726 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519727 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
          channel_count source_name_ch1 organism_ch1 characteristics_ch1 ⋯
GSM519722 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519723 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519724 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519725 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519726 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519727 1             Breast tumor    Homo sapiens quality control: 1  ⋯
          grade:ch1 her2 status:ch1 methylation barcode:ch1 node:ch1
GSM519722 3         1               4690141010_D            1
GSM519723 3         1               4690141010_J            1
GSM519724 3         1               4690141011_A            0
GSM519725 3         0               4690141010_I            1
GSM519726 3         1               4690141011_E            0
GSM519727 3         0               4690141010_K            1
          quality control:ch1 size (bin):ch1 subtypege:ch1 subtypeihc:ch1
GSM519722 1                   1              HER2+         HER2
GSM519723 1                   1              HER2+         HER2
GSM519724 1                   1              HER2+         HER2
GSM519725 1                   1              LumB          LumB
GSM519726 1                   0              Basal         HER2
GSM519727 1                   0              Basal         Basal
          t.os:ch1 t.rfs:ch1
GSM519722 8.28 y   0.93
GSM519723 3.39 y   1.22
GSM519724 8.64 y   8.64
GSM519725 8.4 y    8.4
GSM519726 7.21 y   7.21
GSM519727 8.19 y   7.01

In [326]:
head(view_preprocessed_clinical(datasets[3]))

Preprocessed Clinical: GSE20711 -> 88 rows x 118 cols

  geo_accession is_tumor rfs_event rfs_time
1 GSM519722     1        1          339.6825
2 GSM519723     1        1          445.6050
3 GSM519724     1        0         3155.7600
4 GSM519725     1        0         3068.1000
5 GSM519726     1        0         2633.4525
6 GSM519727     1        1         2560.4025

In [327]:
summarise_rfs_time(datasets[3])

Warning message in summarise_rfs_time(datasets[3]):
"NAs introduced by coercion"

RFS time raw distributionL:  GSE20711
Column: t.rfs:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.000   2.560   5.955   5.615   7.933  14.080       2

### GSE88770

In [328]:
head(view_raw_expr(datasets[4]))

Raw Expression: GSE88770 -> 54675 rows x 119 cols

  ID        GSM2345257 GSM2345258 GSM2345259 GSM2345260 GSM2345261 GSM2345262
1 1007_s_at 10.681277  10.802657  11.001365  10.040305  10.248975  9.956543
2 1053_at    8.159738   7.527161   8.331114   7.640328   7.372783  7.530817
3 117_at     6.093081   6.218630   6.123202   7.689468   6.004692  6.651521
4 121_at     7.778084   8.301535   7.564411   7.632244   7.835956  7.590282
5 1255_g_at  3.150079   3.190410   3.020225   2.857195   2.875915  3.062885
6 1294_at    6.712948   6.920108   7.766302   8.029146   7.707253  7.997286
  GSM2345263 GSM2345264 GSM2345265 ⋯ GSM2345365 GSM2345366 GSM2345367
1 10.785764  10.681655  10.821716  ⋯ 10.454548  10.466526  10.538790
2  8.031239   7.956069   7.410529  ⋯  8.143535   7.931239   7.532532
3  6.365263   5.896828   5.974322  ⋯  6.241452   9.372554   6.038132
4  7.275567   7.732639   7.913801  ⋯  7.600315   7.445740   7.648995
5  2.885085   2.770437   2.817571  ⋯  2.841175   2.814711   2.756995
6  7.763012   8.049655   7.774498  ⋯  7.771451   7.708887   8.232936
  GSM2345368 GSM2345369 GSM2345370 GSM2345371 GSM2345372 GSM2345373
1 10.488697  10.464901  9.954742   11.106150  11.135586  11.383322
2  7.660106   7.914382  7.588485    7.839713   8.298097   7.229432
3  6.186391   5.329259  5.537211    5.699836   6.461560   6.571032
4  7.126868   7.237025  7.460775    7.868601   7.031209   7.894587
5  2.879981   2.813866  2.776217    2.878176   2.996537   2.996122
6  7.893129   7.177375  7.536349    7.839510   7.670078   8.223649
  Gene Symbol
1 DDR1 /// MIR4640
2 RFC2
3 HSPA6
4 PAX8
5 GUCA1A
6 MIR5193 /// UBA7

In [329]:
head(view_preprocessed_expr(datasets[4]))

Preprocessed Expression: GSE88770 -> 21655 rows x 118 cols

  gene_symbol GSM2345257 GSM2345258 GSM2345259 GSM2345260 GSM2345261 GSM2345262
1 A1BG        6.823343   6.841661   7.517482   7.066259   7.407212   7.356098
2 A1BG-AS1    5.380914   4.960461   5.632821   5.161617   5.438206   5.880592
3 A1CF        3.815948   4.142036   4.079639   3.802018   3.970475   4.023918
4 A2M         7.514131   8.185255   8.142596   8.159722   8.364816   8.133507
5 A2M-AS1     5.307615   6.067712   6.313713   6.816215   6.534387   6.264997
6 A2ML1       3.252120   3.498092   3.607268   3.310913   3.254299   3.400641
  GSM2345263 GSM2345264 GSM2345265 ⋯ GSM2345364 GSM2345365 GSM2345366
1 7.154821   7.096108   6.468802   ⋯ 6.976417   5.859655   7.837866
2 5.756559   5.504966   5.310122   ⋯ 5.234477   4.738434   5.330613
3 3.991444   3.832228   3.937628   ⋯ 4.071126   3.888329   4.035238
4 7.736251   7.926599   7.856633   ⋯ 8.756021   8.325534   7.750709
5 5.885880   5.029818   6.038523   ⋯ 6.060199   6.386559   5.476085
6 3.346865   3.238652   3.432481   ⋯ 3.447296   3.347826   3.241430
  GSM2345367 GSM2345368 GSM2345369 GSM2345370 GSM2345371 GSM2345372 GSM2345373
1 6.895554   7.250273   6.311108   6.544339   6.910726   6.550731   5.887219
2 5.585428   5.674181   4.588571   5.184829   5.359352   5.266632   5.406793
3 3.905470   3.873878   3.941997   4.151041   4.146553   3.663920   3.955250
4 7.957422   7.675870   8.209924   8.338146   8.192327   8.389905   8.364993
5 6.461962   6.306009   6.154432   7.147076   6.264936   6.224723   4.847976
6 3.327122   3.256374   3.429618   3.429215   3.312900   3.188677   3.534706

In [330]:
head(view_raw_clinical(datasets[4]))

Raw Clinical: GSE88770 -> 117 rows x 68 cols

  title                                              [117 unique]  character  e.g. PD9888, PD13139, PD13143 ...
  geo_accession                                      [117 unique]  character  e.g. GSM2345257, GSM2345258, GSM2345259 ...
  status                                             [1 unique]  Public on Oct 15 2016
  submission_date                                    [1 unique]  Oct 14 2016
  last_update_date                                   [1 unique]  Oct 15 2016
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [4 unique]  ILC, grade 1 | ILC, grade 2 | ILC, grade 3 | ILC, grade not available
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [1 unique]  disease status: Invasive lobular carcinoma (ILC)
  characteristics_ch1.1                              [1 unique]  gender: Female
  characteristics_ch1.2                              [1 unique]  tissue: Breast cancer tumor
  characteristics_ch1.3                              [1 unique]  tumor type: ILC
  characteristics_ch1.4                              [5 unique]  subtype: Alveolar | subtype: Classic | subtype: Mixed, non classic | subtype: Solid | subtype: Trabecular
  characteristics_ch1.5                              [19 unique]  character  e.g. positive_nodes: 8, positive_nodes: 2, positive_nodes: 0 ...
  characteristics_ch1.6                              [2 unique]  er: Negative | er: Positive
  characteristics_ch1.7                              [3 unique]  pgr: NA | pgr: Negative | pgr: Positive
  characteristics_ch1.8                              [3 unique]  her2: NA | her2: Negative | her2: Positive
  characteristics_ch1.9                              [30 unique]  character  e.g. ki67: 34, ki67: 10, ki67: 5 ...
  characteristics_ch1.10                             [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.11                             [11 unique]  cellularity: 10 | cellularity: 15 | cellularity: 20 | cellularity: 25 | cellularity: 30 | cellularity: 35 | cellularity: 40 | cellularity: 50 | cellularity: 60 | cellularity: 70 | cellularity: 80
  characteristics_ch1.12                             [79 unique]  character  e.g. idfs_or_last_contact_years: 10.9, idfs_or_last_contact_years: 9.7, idfs_or_last_contact_years: 11.2 ...
  characteristics_ch1.13                             [2 unique]  cellularity: No | cellularity: Yes
  characteristics_ch1.14                             [81 unique]  character  e.g. drfs_or_last_contact_years: 10.9, drfs_or_last_contact_years: 9.7, drfs_or_last_contact_years: 12.8 ...
  characteristics_ch1.15                             [2 unique]  drfs_event: No | drfs_event: Yes
  characteristics_ch1.16                             [80 unique]  character  e.g. os_or_last_contact_years: 11.8, os_or_last_contact_years: 10.4, os_or_last_contact_years: 12.8 ...
  characteristics_ch1.17                             [2 unique]  death: No | death: Yes
  characteristics_ch1.18                             [2 unique]  death_disease_specific: No | death_disease_specific: Yes
  treatment_protocol_ch1                             [1 unique]  Not applicable.
  growth_protocol_ch1                                [1 unique]  Not applicable.
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Trizol extraction of total RNA was performed according to the manufacturer's instructions.
  label_ch1                                          [1 unique]  Biotin
  label_protocol_ch1                                 [1 unique]  Biotinylated cRNA were prepared according to the standard Affymetrix protocol from 100 ng total RNA (HuGen U133 Plus 2 array, Affymetrix).
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Following fragmentation, 15 ug of cRNA were hybridized for 16 hr at 45C on GeneChip HG133 Plus 2 Array, Affymetrix. GeneChips were washed and stained in the Affymetrix Fluidics Station 450.
  scan_protocol                                      [1 unique]  GeneChips were scanned using Affymetrix GeneChip Scanner GCS3000.
  description                                        [1 unique]  Gene expression data from breast tumor sample.
  data_processing                                    [1 unique]  The probe level intensities were background adjusted using the Robust multi-array analysis (RMA) method followed by quantile normalization as implemented in the R/Bioconductor package frma.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Yacine,,Bareche
  contact_email                                      [1 unique]  barechey@gmail.com
  contact_laboratory                                 [1 unique]  BCTL
  contact_institute                                  [1 unique]  Jules Bordet Institute
  contact_address                                    [1 unique]  Rue Héger-Bordetstraat 1
  contact_city                                       [1 unique]  Brussel
  contact_zip/postal_code                            [1 unique]  1000
  contact_country                                    [1 unique]  Belgium
  supplementary_file                                 [117 unique]  character  e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345257/suppl/GSM2345257_d7466e64-c302-432a-8b82-5ba7f7701fbb.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345258/suppl/GSM2345258_DNA10452-030.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345259/suppl/GSM2345259_a3fd5ea6-3ce7-4c44-be97-7fe476cc830b.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  cellularity:ch1                                    [19 unique]  character  e.g. 50;Yes, 80;Yes, 25;Yes ...
  death:ch1                                          [2 unique]  No | Yes
  death_disease_specific:ch1                         [2 unique]  No | Yes
  disease status:ch1                                 [1 unique]  Invasive lobular carcinoma (ILC)
  drfs_event:ch1                                     [2 unique]  No | Yes
  drfs_or_last_contact_years:ch1                     [81 unique]  character  e.g. 10.9, 9.7, 12.8 ...
  er:ch1                                             [2 unique]  Negative | Positive
  gender:ch1                                         [1 unique]  Female
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  her2:ch1                                           [3 unique]  NA | Negative | Positive
  idfs_or_last_contact_years:ch1                     [79 unique]  character  e.g. 10.9, 9.7, 11.2 ...
  ki67:ch1                                           [30 unique]  character  e.g. 34, 10, 5 ...
  os_or_last_contact_years:ch1                       [80 unique]  character  e.g. 11.8, 10.4, 12.8 ...
  pgr:ch1                                            [3 unique]  NA | Negative | Positive
  positive_nodes:ch1                                 [19 unique]  character  e.g. 8, 2, 0 ...
  subtype:ch1                                        [5 unique]  Alveolar | Classic | Mixed, non classic | Solid | Trabecular
  tissue:ch1                                         [1 unique]  Breast cancer tumor
  tumor type:ch1                                     [1 unique]  ILC

           title   geo_accession status                submission_date
GSM2345257 PD9888  GSM2345257    Public on Oct 15 2016 Oct 14 2016
GSM2345258 PD13139 GSM2345258    Public on Oct 15 2016 Oct 14 2016
GSM2345259 PD13143 GSM2345259    Public on Oct 15 2016 Oct 14 2016
GSM2345260 PD13148 GSM2345260    Public on Oct 15 2016 Oct 14 2016
GSM2345261 PD9867  GSM2345261    Public on Oct 15 2016 Oct 14 2016
GSM2345262 PD13155 GSM2345262    Public on Oct 15 2016 Oct 14 2016
           last_update_date type channel_count source_name_ch1 organism_ch1
GSM2345257 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345258 Oct 15 2016      RNA  1             ILC, grade 3    Homo sapiens
GSM2345259 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345260 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345261 Oct 15 2016      RNA  1             ILC, grade 1    Homo sapiens
GSM2345262 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
           characteristics_ch1                              ⋯ grade:ch1
GSM2345257 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345258 disease status: Invasive lobular carcinoma (ILC) ⋯ 3
GSM2345259 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345260 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345261 disease status: Invasive lobular carcinoma (ILC) ⋯ 1
GSM2345262 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
           her2:ch1 idfs_or_last_contact_years:ch1 ki67:ch1
GSM2345257 Negative 10.9                           34
GSM2345258 Negative 9.7                            10
GSM2345259 Negative 11.2                           5
GSM2345260 NA       7.3                            18
GSM2345261 Negative 7.9                            11
GSM2345262 Negative 8.6                            67.5
           os_or_last_contact_years:ch1 pgr:ch1  positive_nodes:ch1 subtype:ch1
GSM2345257 11.8                         Positive 8                  Trabecular
GSM2345258 10.4                         Negative 2                  Solid
GSM2345259 12.8                         Negative 0                  Trabecular
GSM2345260 13.7                         Positive 0                  Classic
GSM2345261 14.8                         Positive 2                  Classic
GSM2345262 8.6                          Positive 0                  Trabecular
           tissue:ch1          tumor type:ch1
GSM2345257 Breast cancer tumor ILC
GSM2345258 Breast cancer tumor ILC
GSM2345259 Breast cancer tumor ILC
GSM2345260 Breast cancer tumor ILC
GSM2345261 Breast cancer tumor ILC
GSM2345262 Breast cancer tumor ILC

In [331]:
head(view_preprocessed_clinical(datasets[4]))

Preprocessed Clinical: GSE88770 -> 117 rows x 118 cols

  geo_accession is_tumor rfs_event rfs_time
1 GSM2345257    1        1         3981.225
2 GSM2345258    1        1         3542.925
3 GSM2345259    1        0         4675.200
4 GSM2345260    1        0         5003.925
5 GSM2345261    1        1         2885.475
6 GSM2345262    1        0         3141.150

In [332]:
summarise_rfs_time(datasets[4])

RFS time raw distributionL:  GSE88770
Column: drfs_or_last_contact_years:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.200   5.900   8.600   8.745  11.000  17.800