In [1]:
import pandas as pd
import os

In [2]:
expr_filename = "../datasets/csv_files/expression_matrix_test_one.csv"
clinical_filename = "../datasets/csv_files/clinical_metadata_test_one.csv"

# load datasets
expr = pd.read_csv(expr_filename)
clinical = pd.read_csv(clinical_filename)

clinical.tail()

,Unnamed: 0,sample_id,is_tumor,patient_age,tumor_grade,t_stage,er_status,lymph_node_status,relapse_free_event,relapse_free_time
261,GSM540369,GSM540369,1,52.0,3.0,3.0,0.0,1.0,0.0,246.0
262,GSM540370,GSM540370,1,70.0,3.0,2.0,0.0,1.0,0.0,235.0
263,GSM540371,GSM540371,1,61.0,3.0,3.0,0.0,1.0,1.0,365.0
264,GSM540372,GSM540372,1,64.0,3.0,2.0,0.0,1.0,0.0,349.0
265,GSM540373,GSM540373,1,73.0,3.0,2.0,0.0,1.0,0.0,234.0

In [3]:
# rename column for clarity
expr = expr.iloc[:, 1:]
clinical = clinical.drop(columns=['sample_id'])
clinical.rename(columns={'Unnamed: 0': 'sample_name'}, inplace=True)

In [4]:
expr.head()

,gene_symbol,GSM540108,GSM540109,GSM540110,GSM540111,GSM540112,GSM540113,GSM540114,GSM540115,GSM540116,...,GSM540364,GSM540365,GSM540366,GSM540367,GSM540368,GSM540369,GSM540370,GSM540371,GSM540372,GSM540373
0,A1BG,6.146570,5.632868,7.407916,5.717083,5.667256,5.821602,5.582540,5.678218,6.570997,...,5.768699,5.915461,5.332402,5.880671,5.785042,6.160731,5.855461,5.794792,5.933755,5.574898
1,A1BG-AS1,5.192952,6.270687,5.594629,4.476920,5.047257,5.420414,4.874277,4.710615,5.320223,...,4.654715,4.821310,4.533131,4.630453,4.559740,4.400831,4.790866,4.519228,4.606000,4.458904
2,A1CF,4.136334,4.220885,4.546149,3.887450,3.876345,3.737222,3.619344,3.747788,3.939471,...,3.730873,3.814982,3.800488,3.891974,3.807973,3.815930,3.925795,3.902201,4.093958,3.588490
3,A2M,7.202705,6.328396,8.172368,8.021876,7.659437,8.497944,8.218462,8.664218,8.092863,...,8.240868,8.781016,8.344433,7.989748,9.159850,8.391154,7.977827,8.225967,8.341430,8.060287
4,A2M-AS1,5.378281,4.429702,6.103873,5.039355,4.568131,5.923578,5.995361,6.468561,4.866476,...,6.963635,5.482779,4.767218,5.862145,5.259731,4.957411,4.985096,5.038558,4.602791,6.741662

In [5]:
clinical.head()

,sample_name,is_tumor,patient_age,tumor_grade,t_stage,er_status,lymph_node_status,relapse_free_event,relapse_free_time
0,GSM540108,1,67.0,2.0,2.0,1.0,1.0,1.0,731.0
1,GSM540109,1,47.0,3.0,NaN,0.0,1.0,1.0,NaN
2,GSM540110,1,41.0,3.0,NaN,1.0,1.0,1.0,NaN
3,GSM540111,1,62.0,3.0,1.0,0.0,1.0,1.0,1770.0
4,GSM540112,1,60.0,2.0,2.0,1.0,1.0,1.0,871.0

In [6]:
# save datasets
expr.to_csv(expr_filename, index=False)
clinical.to_csv(clinical_filename, index=False)