In [1]:
import pandas as pd

In [2]:
expr_filename = "../datasets/csv_files/deg_expression_matrix_train.csv"
clinical_filename = "../datasets/csv_files/clinical_metadata_train.csv"

# load datasets
expr = pd.read_csv(expr_filename)
clinical = pd.read_csv(clinical_filename)

expr.tail()

,Unnamed: 0,ACO1,ADAR,ADIPOQ,AGPAT2,ALDOC,ANG,ANGPT1,ANXA1,AP1M2,...,UBE2S,VAMP3,VAMP8,VAV3,VIM,VSIG4,VTCN1,WASF3,XG,ZBTB16
116,GSM1045307,5.203403,10.959269,8.702324,7.041712,5.648214,6.406124,3.431597,6.256545,7.370626,...,5.353391,6.855845,9.331770,6.207411,8.004465,5.791495,7.566206,5.456396,3.526410,5.548989
117,GSM1045308,5.127605,11.360866,7.397231,6.544511,4.872048,5.745155,3.406306,6.233634,7.440081,...,4.538992,6.992438,9.225429,7.163821,7.131669,4.832512,10.095019,4.740242,3.570365,5.561340
118,GSM1045309,5.042086,11.477019,7.884212,6.754487,5.677034,5.703791,3.649727,6.059804,7.297497,...,4.286536,6.151536,8.961976,5.970050,8.021949,5.416392,6.009214,4.934460,3.598006,4.083736
119,GSM1045310,4.999178,11.684356,7.978151,6.882038,6.395405,7.028010,3.401648,5.549689,8.045023,...,5.416381,7.043281,9.422541,6.350747,7.942938,5.949860,10.447985,4.626388,3.556260,6.827443
120,GSM1045311,4.704057,11.372424,9.344512,6.969142,7.071158,6.710324,3.395278,6.570024,7.990833,...,5.775663,7.399192,8.992688,6.434351,8.371146,6.234255,9.501296,4.790300,3.565238,4.551610

In [3]:
# rename column for clarity
#expr_filtered = expr.iloc[:, 1:]
clinical_filtered = clinical.drop(columns=['sample_id'])
clinical_filtered.rename(columns={'Unnamed: 0': 'sample_name'}, inplace=True)
expr_filtered = expr.rename(columns={'Unnamed: 0': 'sample_name'})

In [4]:
expr_filtered.head()

,sample_name,ACO1,ADAR,ADIPOQ,AGPAT2,ALDOC,ANG,ANGPT1,ANXA1,AP1M2,...,UBE2S,VAMP3,VAMP8,VAV3,VIM,VSIG4,VTCN1,WASF3,XG,ZBTB16
0,GSM1045191,6.697765,9.719198,11.876584,8.604980,8.414169,7.941133,6.564200,9.817748,5.556355,...,4.445544,8.155041,7.942988,4.577871,10.001357,7.563904,6.866327,9.021858,4.897770,8.081731
1,GSM1045192,5.872591,9.678302,7.153605,6.503194,4.581926,4.814703,3.905613,7.074081,5.120402,...,4.422642,7.358038,9.970144,4.369697,8.650840,7.693408,4.912463,4.480019,3.334647,4.078880
2,GSM1045193,4.704279,10.457587,5.392332,6.142293,6.235045,4.186915,3.946060,4.031208,4.889919,...,4.878597,6.282494,8.971080,4.458827,7.124404,5.279563,4.479120,4.514484,3.458176,4.305987
3,GSM1045194,4.650540,9.122421,5.247072,6.581231,6.079837,5.460042,4.049906,6.102090,6.759978,...,4.498002,6.274657,8.636839,5.733220,7.628729,4.990067,7.731202,5.544438,3.338516,5.512143
4,GSM1045195,8.647494,10.151534,12.136559,9.370264,8.294877,8.182388,6.256205,10.263854,4.763354,...,4.847608,8.498974,7.105619,4.054034,10.257068,7.878502,6.027630,8.935739,6.005618,7.841789

In [5]:
clinical_filtered.head()

,sample_name,is_tumor,patient_age,tumor_grade,tumor_size,er_status,lymph_node_status,relapse_free_event,relapse_free_time
0,GSM1045191,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GSM1045192,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GSM1045193,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GSM1045194,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GSM1045195,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# save datasets
expr_filtered.to_csv(expr_filename, index=False)
clinical_filtered.to_csv(clinical_filename, index=False)