In [1]:
import pandas as pd

In [2]:
expr_filename = "../datasets/csv_files/expression_matrix_test_two.csv"
clinical_filename = "../datasets/csv_files/clinical_metadata_test_two.csv"

# load datasets
expr = pd.read_csv(expr_filename)
clinical = pd.read_csv(clinical_filename)

expr.tail()

,Unnamed: 0,gene_symbol,GSM519722,GSM519723,GSM519724,GSM519725,GSM519726,GSM519727,GSM519728,GSM519729,...,GSM519803,GSM519804,GSM519805,GSM519806,GSM519807,GSM519808,GSM519809,GSM519810,GSM519811,GSM519812
21650,21651,ZYG11B,7.183321,7.418680,7.409676,7.610468,7.285693,6.906873,7.448420,7.943742,...,7.207707,7.193726,6.986243,6.989238,7.095653,7.031124,7.243179,7.118969,7.320579,7.335627
21651,21652,ZYX,7.117127,6.539444,7.749218,6.419296,7.204199,6.570390,6.729389,6.653874,...,6.740223,6.348942,6.734496,5.971702,6.550986,6.499999,6.805447,6.547173,7.000272,6.767400
21652,21653,ZZEF1,5.326840,5.408874,5.416818,5.246277,5.308182,5.336418,5.303648,5.722966,...,5.401952,5.250886,4.957407,5.459612,5.484043,5.324387,5.579983,5.510067,5.489594,5.614031
21653,21654,ZZZ3,6.888598,7.198831,7.541631,7.542585,7.823545,7.144670,8.102524,6.716392,...,7.085738,7.727790,7.679852,7.281497,7.833954,6.982578,7.630663,7.672551,8.142662,7.570256
21654,21655,mir-223,3.348883,3.170089,4.304604,3.766448,3.683761,4.152305,3.569500,3.919936,...,3.732516,4.642317,3.696336,3.302339,3.637847,4.154121,4.119092,4.042529,3.708584,3.785074

In [3]:
# rename column for clarity
expr_filtered = expr.iloc[:, 1:]
clinical_filtered = clinical.drop(columns=['sample_id'])
clinical_filtered.rename(columns={'Unnamed: 0': 'sample_name'}, inplace=True)
# expr_filtered = expr.rename(columns={'Unnamed: 0': 'sample_name'})

In [4]:
expr_filtered.head()

,gene_symbol,GSM519722,GSM519723,GSM519724,GSM519725,GSM519726,GSM519727,GSM519728,GSM519729,GSM519730,...,GSM519803,GSM519804,GSM519805,GSM519806,GSM519807,GSM519808,GSM519809,GSM519810,GSM519811,GSM519812
0,A1BG,6.119304,6.479491,6.017579,6.061706,5.581822,5.745512,4.886712,5.426486,5.901916,...,6.828642,6.224153,5.904253,7.912051,5.955679,5.698015,6.037793,5.715892,5.262424,5.574846
1,A1BG-AS1,4.600823,4.603668,5.055174,4.647037,4.182169,4.702075,4.326911,4.773466,4.570657,...,5.165543,5.413369,4.413916,5.295210,4.995111,4.816337,4.585186,4.774603,4.412655,4.546656
2,A1CF,3.121685,3.268132,3.115821,3.169886,3.329781,3.369047,3.217963,3.303424,3.170489,...,3.436043,3.180104,3.173097,3.547779,3.180838,3.681620,3.463427,3.442144,3.177729,3.593152
3,A2M,7.234631,7.518227,7.381913,7.575412,8.363513,7.212989,7.100545,7.251371,7.344661,...,6.895032,7.326967,7.521037,6.383923,7.135244,7.712773,7.493888,7.007678,7.672010,7.781730
4,A2M-AS1,4.909697,5.186144,7.623446,6.109816,6.142342,5.984419,4.648674,5.765407,5.374764,...,4.911827,7.175151,6.366014,4.906894,5.463223,4.654847,5.819628,5.777034,6.470250,6.035571

In [5]:
clinical_filtered.head()

  sample_name  is_tumor  relapse_free_event  relapse_free_time
0   GSM519722         1                 1.0              339.0
1   GSM519723         1                 1.0              445.0
2   GSM519724         1                 0.0             3155.0
3   GSM519725         1                 0.0             3068.0
4   GSM519726         1                 0.0             2633.0

In [6]:
# save datasets
expr_filtered.to_csv(expr_filename, index=False)
clinical_filtered.to_csv(clinical_filename, index=False)