In [1]:
import pandas as pd

In [2]:
expr_filename = "../datasets/csv_files/expression_matrix_train.csv"
clinical_filename = "../datasets/csv_files/clinical_metadata_train.csv"

# load datasets
expr = pd.read_csv(expr_filename)
clinical = pd.read_csv(clinical_filename)

expr.tail()

,gene_symbol,GSM1045191,GSM1045192,GSM1045193,GSM1045194,GSM1045195,GSM1045196,GSM1045197,GSM1045198,GSM1045199,...,GSM1045302,GSM1045303,GSM1045304,GSM1045305,GSM1045306,GSM1045307,GSM1045308,GSM1045309,GSM1045310,GSM1045311
21650,ZYG11B,6.580087,5.245011,4.068935,4.824514,6.760732,7.025029,6.556421,6.499272,7.211577,...,4.088098,5.818421,5.478780,4.880009,5.855989,5.447839,6.245823,4.985343,5.575799,5.542681
21651,ZYX,5.938598,6.762844,5.696243,5.600152,6.342158,6.291689,6.453661,6.243340,6.269302,...,6.036016,6.115108,6.296688,6.989170,5.449913,6.483694,5.873504,5.660989,6.371205,6.424540
21652,ZZEF1,5.002839,5.005206,4.905546,4.533484,5.078449,5.023273,4.846593,4.909262,4.955776,...,4.643335,4.818367,5.146947,5.356448,4.263618,4.992205,4.637800,5.068945,5.384980,4.812244
21653,ZZZ3,6.569073,5.850447,6.710517,6.040400,6.137959,6.897657,6.401516,6.520239,6.647114,...,4.530377,6.907677,7.149789,6.036685,6.657916,6.871425,7.061236,6.326525,6.185247,6.212941
21654,mir-223,3.163245,2.952650,4.035940,3.700845,2.836687,3.220634,3.276715,3.025565,3.292066,...,3.152534,3.064251,2.766617,2.896108,3.020869,2.741222,2.741222,3.063522,2.943168,2.811689

In [3]:
# rename column for clarity
expr_filtered = expr.iloc[:, 1:]
clinical_filtered = clinical.drop(columns=['sample_id'])
clinical_filtered.rename(columns={'Unnamed: 0': 'sample_name'}, inplace=True)
# expr_filtered = expr.rename(columns={'Unnamed: 0': 'sample_name'})

In [4]:
expr_filtered.head()

,gene_symbol,GSM519722,GSM519723,GSM519724,GSM519725,GSM519726,GSM519727,GSM519728,GSM519729,GSM519730,...,GSM519803,GSM519804,GSM519805,GSM519806,GSM519807,GSM519808,GSM519809,GSM519810,GSM519811,GSM519812
0,A1BG,6.119304,6.479491,6.017579,6.061706,5.581822,5.745512,4.886712,5.426486,5.901916,...,6.828642,6.224153,5.904253,7.912051,5.955679,5.698015,6.037793,5.715892,5.262424,5.574846
1,A1BG-AS1,4.600823,4.603668,5.055174,4.647037,4.182169,4.702075,4.326911,4.773466,4.570657,...,5.165543,5.413369,4.413916,5.295210,4.995111,4.816337,4.585186,4.774603,4.412655,4.546656
2,A1CF,3.121685,3.268132,3.115821,3.169886,3.329781,3.369047,3.217963,3.303424,3.170489,...,3.436043,3.180104,3.173097,3.547779,3.180838,3.681620,3.463427,3.442144,3.177729,3.593152
3,A2M,7.234631,7.518227,7.381913,7.575412,8.363513,7.212989,7.100545,7.251371,7.344661,...,6.895032,7.326967,7.521037,6.383923,7.135244,7.712773,7.493888,7.007678,7.672010,7.781730
4,A2M-AS1,4.909697,5.186144,7.623446,6.109816,6.142342,5.984419,4.648674,5.765407,5.374764,...,4.911827,7.175151,6.366014,4.906894,5.463223,4.654847,5.819628,5.777034,6.470250,6.035571

In [5]:
clinical_filtered.head()

  sample_name  is_tumor  relapse_free_event  relapse_free_time
0   GSM519722         1                 1.0              339.0
1   GSM519723         1                 1.0              445.0
2   GSM519724         1                 0.0             3155.0
3   GSM519725         1                 0.0             3068.0
4   GSM519726         1                 0.0             2633.0

In [6]:
# save datasets
expr_filtered.to_csv(expr_filename, index=False)
clinical_filtered.to_csv(clinical_filename, index=False)