In [12]:
import pandas as pd
import os

In [13]:
expr_filename = "../datasets/csv_files/expression_matrix_test_one.csv"
clinical_filename = "../datasets/csv_files/clinical_metadata_test_one.csv"

# load datasets
expr = pd.read_csv(expr_filename)
clinical = pd.read_csv(clinical_filename)

expr.tail()

,sample_name,gene_symbol,GSM540108,GSM540109,GSM540110,GSM540111,GSM540112,GSM540113,GSM540114,GSM540115,...,GSM540364,GSM540365,GSM540366,GSM540367,GSM540368,GSM540369,GSM540370,GSM540371,GSM540372,GSM540373
21650,21651,ZYG11B,6.635957,6.957342,7.299554,7.852998,7.861657,8.174834,7.816731,8.500056,...,7.069218,6.933989,7.536102,7.360584,7.938927,7.888732,7.656595,7.438104,7.798040,7.784161
21651,21652,ZYX,8.039407,8.101518,8.195125,9.684551,8.696353,10.332553,9.150694,9.874273,...,9.773243,10.421647,10.277477,10.101851,10.336445,9.251954,9.580896,9.808302,10.107726,9.739957
21652,21653,ZZEF1,6.266267,5.852577,6.125562,5.897437,5.889624,6.433840,5.927160,5.873355,...,6.269974,6.291125,5.831139,6.187754,5.970918,5.924909,5.895422,5.930023,6.147534,6.197190
21653,21654,ZZZ3,6.821724,6.055815,6.990111,7.499180,7.680644,6.908704,7.267744,7.553148,...,7.488613,7.293796,8.289701,8.237561,7.991368,8.007629,6.978497,7.196792,7.708420,7.830055
21654,21655,mir-223,4.431420,4.392363,4.064667,4.209039,3.751116,4.178111,4.591735,5.908435,...,5.077201,5.369013,3.669674,3.651762,3.638527,3.946568,3.793919,4.283540,3.674172,4.864194

In [16]:
# rename column for clarity
expr_filtered = expr.iloc[:, 1:]
# clinical_filtered = clinical.drop(columns=['sample_id'])
# clinical_filtered.rename(columns={'Unnamed: 0': 'sample_name'}, inplace=True)
# expr_filtered = expr.rename(columns={'Unnamed: 0': 'sample_name'})

In [17]:
expr_filtered.head()

,gene_symbol,GSM540108,GSM540109,GSM540110,GSM540111,GSM540112,GSM540113,GSM540114,GSM540115,GSM540116,...,GSM540364,GSM540365,GSM540366,GSM540367,GSM540368,GSM540369,GSM540370,GSM540371,GSM540372,GSM540373
0,A1BG,6.146570,5.632868,7.407916,5.717083,5.667256,5.821602,5.582540,5.678218,6.570997,...,5.768699,5.915461,5.332402,5.880671,5.785042,6.160731,5.855461,5.794792,5.933755,5.574898
1,A1BG-AS1,5.192952,6.270687,5.594629,4.476920,5.047257,5.420414,4.874277,4.710615,5.320223,...,4.654715,4.821310,4.533131,4.630453,4.559740,4.400831,4.790866,4.519228,4.606000,4.458904
2,A1CF,4.136334,4.220885,4.546149,3.887450,3.876345,3.737222,3.619344,3.747788,3.939471,...,3.730873,3.814982,3.800488,3.891974,3.807973,3.815930,3.925795,3.902201,4.093958,3.588490
3,A2M,7.202705,6.328396,8.172368,8.021876,7.659437,8.497944,8.218462,8.664218,8.092863,...,8.240868,8.781016,8.344433,7.989748,9.159850,8.391154,7.977827,8.225967,8.341430,8.060287
4,A2M-AS1,5.378281,4.429702,6.103873,5.039355,4.568131,5.923578,5.995361,6.468561,4.866476,...,6.963635,5.482779,4.767218,5.862145,5.259731,4.957411,4.985096,5.038558,4.602791,6.741662

In [18]:
clinical_filtered.head()

,sample_name,is_tumor,patient_age,tumor_grade,t_stage,er_status,lymph_node_status,relapse_free_event,relapse_free_time
0,GSM540108,1,67.0,2.0,2.0,1.0,1.0,1.0,731.0
1,GSM540109,1,47.0,3.0,NaN,0.0,1.0,1.0,NaN
2,GSM540110,1,41.0,3.0,NaN,1.0,1.0,1.0,NaN
3,GSM540111,1,62.0,3.0,1.0,0.0,1.0,1.0,1770.0
4,GSM540112,1,60.0,2.0,2.0,1.0,1.0,1.0,871.0

In [19]:
# save datasets
expr_filtered.to_csv(expr_filename, index=False)
clinical_filtered.to_csv(clinical_filename, index=False)