In [3]:
library(survival)

In [5]:
expr <- readRDS("../datasets/expression_matrix_train.rds")
clinical <- readRDS("../datasets/clinical_metadata_train.rds")

head(expr)
head(clinical)

  gene_symbol GSM1045191 GSM1045192 GSM1045193 GSM1045194 GSM1045195 GSM1045196
1 A1BG        5.061765   5.384287   5.462018   5.104647   4.940101   5.087535
2 A1BG-AS1    4.213439   4.497735   5.442854   4.142935   3.836375   3.840813
3 A1CF        2.960794   3.844863   3.603847   3.710878   2.919968   3.246907
4 A2M         6.814863   6.845371   4.532851   7.000975   7.117619   6.683618
5 A2M-AS1     4.973031   4.252506   3.920574   4.064233   5.378826   5.553602
6 A2ML1       3.133812   3.408455   3.779359   3.546180   3.138060   3.030034
  GSM1045197 GSM1045198 GSM1045199 ⋯ GSM1045302 GSM1045303 GSM1045304
1 5.647719   5.502169   4.935021   ⋯ 5.612234   5.074677   6.872525
2 4.108047   4.117811   4.374573   ⋯ 5.274847   4.386748   5.158049
3 2.954523   3.181512   3.115969   ⋯ 3.695726   3.247118   3.037334
4 6.839982   7.182724   6.365128   ⋯ 5.206523   6.804822   6.542975
5 5.198546   5.391066   5.675315   ⋯ 3.974318   4.694706   4.407413
6 3.338255   3.241485   3.111028   ⋯ 4.034024   3.141456   3.195094
  GSM1045305 GSM1045306 GSM1045307 GSM1045308 GSM1045309 GSM1045310 GSM1045311
1 8.020731   5.132484   5.815884   5.310448   5.293781   5.683640   5.880834
2 4.650182   4.528774   4.627988   4.577176   4.533182   4.283014   4.635586
3 3.657515   3.350718   2.967194   2.943969   3.404410   3.238819   2.898562
4 5.768323   5.881436   6.835486   6.455288   6.328355   6.584059   6.576534
5 3.791085   3.544270   4.649494   3.700493   3.785728   3.637337   4.267453
6 3.162890   3.291446   2.894613   2.764031   3.472512   3.094196   3.243091

           sample_id  tissue_type   patient_age tumor_grade tumor_size
GSM1045191 GSM1045191 normal breast NA          NA          NA
GSM1045192 GSM1045192 normal breast NA          NA          NA
GSM1045193 GSM1045193 normal breast NA          NA          NA
GSM1045194 GSM1045194 normal breast NA          NA          NA
GSM1045195 GSM1045195 normal breast NA          NA          NA
GSM1045196 GSM1045196 normal breast NA          NA          NA
           er_status lymph_node_status relapse_free_event relapse_free_time
GSM1045191 NA        NA                NA                 NA
GSM1045192 NA        NA                NA                 NA
GSM1045193 NA        NA                NA                 NA
GSM1045194 NA        NA                NA                 NA
GSM1045195 NA        NA                NA                 NA
GSM1045196 NA        NA                NA                 NA
           overall_survival_event overall_survival_time
GSM1045191 NA                     NA
GSM1045192 NA                     NA
GSM1045193 NA                     NA
GSM1045194 NA                     NA
GSM1045195 NA                     NA
GSM1045196 NA                     NA